### ISSUE TITLE
how to send a message along with a variable from previous steps

### ISSUE THREAD

**Issue by BatDroid** [zulip/github-actions-zulip#114]
Hi,
let's say I have a step like this

```
      - name: Send a stream message
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_BOT_EMAIL}}
          organization-url: ${{ secrets.ZULIP_ORGANIZATION }}
          to: "channel"
          type: "stream"
          topic: "the topic"
          content: "here is a link generated from latest step"
```

is it possible that I include the variable (which will be a link) from previous step in `content` string?
